;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	evil-delete
	evil-inner-symbol
	evil-next-line
	evil-normal-state
	evil-previous-line
	evil-visual-char
	kill-region
	lalopmak-evil-backward-char
	lalopmak-evil-forward-char
	))

(setq mc/cmds-to-run-once
      '(
	ccm-mwheel-scroll
	smex
	))
